spring.application.name=identity-service-pfe
spring.config.import=optional:configserver:http://localhost:8888
#after that when we will come to docker for making container we have to use the variable environment